# Site settings
email: "contact@pratyush.info"
baseurl: "http://pratyush.info"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Pratyush Srivastava
description: Simplicity . Silence . Surrender
url: "http://www.facebook.com/pratyush272page"
twitter_username: pratyush272
default_img: 

# Profile settings
name: Pratyush Srivastava
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
