# Site settings
email: contact@pratyush.info
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-61692228-1

# SEO settings
title: Pratyush Srivastava
description: Simplicity . Silence . Surrender
url: "http://pratyush.info"
twitter_username: pratyush272
default_img: 

# Profile settings
name: Pratyush Srivastava
profile_img: https://scontent.fdel11-1.fna.fbcdn.net/v/t1.0-9/18119041_1776322932682470_6072869664532898764_n.jpg?oh=3b81dbc860a1b1a314a12eefba4e6761&oe=5AFD8B94
profile: Engineer by popular demand, clueless by choice.
social:
  twitter: http://www.twitter.com/pratyush272
  facebook: http://www.facebook.com/pratyushsrivastavapage
  instagram: http://instagram.com/pratyush272
  youtube: https://www.youtube.com/channel/UC9g-VTTekAtqRukWDvi5B7A

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
