# Site settings
email: contact@pratyush.info
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-61692228-1

# SEO settings
title: Pratyush Srivastava
description: Simplicity . Silence . Surrender
url: "http://pratyush.info"
twitter_username: pratyush272
default_img: 

# Profile settings
name: Pratyush Srivastava
profile_img: 
profile: Engineer by popular demand, clueless by choice.
social:
  github: http://www.github.com/pratyush272
  twitter: http://www.twitter.com/pratyush272
  facebook: http://www.facebook.com/pratyush272page

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
